### ISSUE TITLE
说实话这个方案真的很low比

### ISSUE THREAD

**Issue by chuxin2019s** [dcloudio/uni-template-login#4]
如果是需要登录后进去tabbar使用这种方案的话，那么还得单独去弄一个提示。如果说用户已登录就直接进去tabbar首页，如果没登录就直接进去登录页这种方案真的很low。还不如直接首页弄一个白屏，然后用你们的特性，检测用户是否登录后载入相应的页面，然后手动关闭开屏页。开屏页样式BUG多久了，还没修复，做产品这样搞迟早把自己搞死

**Comment by cubebbox** [comment]
注意言辞，是非常low B

**Comment by zhetengbiji** [comment]
可以看一下代码里有注释，并非要弹出提示。
示例弹出提示，只是一种选择，有注释说明。
另外这个开源的示例，大伙都可以提交 pr ，不知道为何你们要在 issue 发布这种侮辱性的言论。
