### ISSUE TITLE
传说中的第三方登录的代码在哪里？

### ISSUE THREAD

**Issue by layasntx** [dcloudio/uni-template-login#5]
我想知道你们到底有没有多端微信授权登录的DEMO？

**Comment by zhetengbiji** [comment]
> 我想知道你们到底有没有多端微信授权登录的DEMO？

具体什么问题？

**Comment by alexhmyang** [comment]
![image](https://user-images.githubusercontent.com/10215059/92849808-4f9b5e80-f41e-11ea-87ee-519644a88ed8.png)

demo里没有 第三方登录的 功能啊

**Comment by hbcui1984** [comment]
> ![image](https://user-images.githubusercontent.com/10215059/92849808-4f9b5e80-f41e-11ea-87ee-519644a88ed8.png)
> 
> demo里没有 第三方登录的 功能啊

App端菜支持三方登录，H5平台暂无。
