### ISSUE TITLE
what is the wx.xxx api and is this Pro still in Maintain？

### ISSUE THREAD

**Issue by CodingYiyi** [dcloudio/uni-template-login#7]
I just can't understand the reason why using "wx.request" api for a http request in the http.js file.
`if (options.url && options.method) {
			wx.request(options); // <- this
		} else {`
is this wx.XXX api a common use in other platform like H5 or IOS ? 
since the README.md file declared this pro can Run in the android or ios platform.

**Comment by zhetengbiji** [comment]
你检查一下你的问题，是不是想发错地方了？

**Comment by CodingYiyi** [comment]
solly,solly my fault
